### ISSUE TITLE
expect().to.emit.withArgs fails when 2 contract trigger the same event

### ISSUE THREAD

**Issue by Amxx** [EthWorks/Waffle#100]
I have a case where a transaction triggers the same event on 2 contracts with different arg:

→ contractA emits SuccessCall(1)
→ contractB emits SuccessCall(0)

If I try

    expect(...).to.emit(contractA, "SuccessCall").withArgs(1).emit(contractB, "SuccessCall").withArgs(0)

I get an error (from arguments for the call). It looks like the filtering on contract address in not done properly ... I'm also wondering what would happen is a single contract was to emit the same event multiple times with different args.

**Comment by sz-piotr** [comment]
We will be happy to accept a PR that solves this!

**Comment by rzadp** [comment]
- [ ] Same event on 2 contracts
- [ ] Same event on 1 contract with multiple args
