### ISSUE TITLE
Check for empty bytecode before finishing compilation

### ISSUE THREAD

**Issue by AlexXiong97** [EthWorks/Waffle#104]
It might make sense to catch/double-check empty bytecode field, as hinted by @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll in counterfactual/monorepo#1326, which may happen sometimes.

**Comment by marekkirejczyk** [comment]
It seems to me that empty bytecode fields are ok. They are produced for interfaces and interface-like classes. We still might want to use abi. Do I miss something?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
@marekkirejczyk yeah, they are OK for interfaces, but it would be nice if waffle could catch when I try to deploy a contract with empty bytecode)

**Comment by marekkirejczyk** [comment]
oh you mean with `deployContract()`?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
@marekkirejczyk yeap!

**Comment by marekkirejczyk** [comment]
Implemented in [2.0.16](https://github.com/EthWorks/Waffle/releases/tag/2.0.16) @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll @AlexXiong97
