### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by marekkirejczyk** [EthWorks/Waffle#108]
More info on functions:
e.g. deploy a contract:
`token = await deployContract(wallet, BasicTokenMock, [wallet.address, 1000]);`
What each argument is doing?

More step-by-step intro:
- link to install npm/yarn
- create folder

**Comment by sz-piotr** [comment]
Maybe we should revisit this now, as documentation has been updated

**Comment by sz-piotr** [comment]
Closing, as the documentation seems fine now. We will definitely want to put more effort into it as part of Waffle 3
