### ISSUE TITLE
Add dynamic Smart Contracts mocking

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#109]
## Motivation:
Common pattern in Smart Contract testing is to create mock smart contracts for testing.
Examples can be found here:
- [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/mocks)
- [Maker](https://github.com/makerdao/dss/tree/master/src/test)
- [Connext](https://github.com/ConnextProject/indra/tree/staging/modules/contracts/contracts/funding/test-fixtures)
- [Gnosis safe](https://github.com/gnosis/safe-contracts/tree/development/contracts/mocks)

Outside of the blockchain space it is common to use dynamic mocking instead. This reduces amount of code and allow to avoid context switching when writing and reading tests.

An example:
```ts
import { createMock } from '@ethereum-waffle/mock';

// setup mock

const tokenMock = await createMock(wallet, [
  'function balanceOf(address holder) view returns (uint)',
]);
const someContract = someContractFactory.deploy(tokenMock.address);

// test against it

it('reverts if no balance', async () => {
  await tokenMock.balanceOf.returns('0'); 
  await expect(someContract.check()).to.be.revertedWith('Not enough balance');
});

it('returns true if positive balance', async () => {
  await tokenMock.balanceOf.returns('1000000')); 
  expect(await someContract.check()).to.equal(true);
});
```

Related feature: #229

The code will be based on [Doppelganger](https://github.com/EthWorks/Doppelganger), but will come with a range of novel features and improvements. The result should also include better documentation and tutorial.

**Comment by marekkirejczyk** [comment]
Released in Waffle 3.0
