### ISSUE TITLE
Expose ganache config options in waffle-config.json

### ISSUE THREAD

**Issue by karlfloersch** [EthWorks/Waffle#112]
Is it possible to set the ganache options in the waffle config?

If not it would be lovely to add this. In particular it would just mean exposing https://github.com/EthWorks/Waffle/blob/88f91880f0c38592c86137f90862713eb0f9f636/lib/waffle.ts#L12 

This can be very useful for enabling the ganache logger for instance.

Thank you for this fantastic library though!

**Comment by marekkirejczyk** [comment]
Hi @karlfloersch,

Thank you for the proposal :)

Implemented in #133
Released in [2.1.0](https://github.com/EthWorks/Waffle/releases/tag/2.1.0)

Docs available here:
https://ethereum-waffle.readthedocs.io/en/latest/features.html#create-a-mock-provider

Closing, but feedback welcome ;)
