### ISSUE TITLE
Follow semantic versioning for releases

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#118]
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

https://semver.org/

Currently PATCH is updated when new features are added (instead of MINOR).

**Comment by marekkirejczyk** [comment]
Ok, will do.
