### ISSUE TITLE
Library functions blow up

### ISSUE THREAD

**Issue by stonecoldpat** [EthWorks/Waffle#145]
Hi all,

I am trying to build a library with functions (i.e. using "self") to use in a main contract. An example is here:
https://pastebin.com/haz3jMrr

The issue is that, when I write the main contract and uncomment either two lines of code :

`function testme(PaddyInfo.PaddyAppointment memory _appointment) public payable returns (bool) {
 
        // It breaks when we uncomment the below functions
        // bytes32 appointmentid = _appointment.computeAppointmentID();
        // bytes32 sigHash = _appointment.computeEncodedAppointmentHash();
 
        return true;
    }`

Then when I try to compile everything ('npx waffle'), the compiler just blows up. 
![Screen Shot 2019-10-19 at 06 41 19](https://user-images.githubusercontent.com/6450946/67138472-83382d80-f23b-11e9-9bc9-54ce7f36f404.png)

It looks like it is not compiling correctly and I'm not totally sure what to do. Is this a problem with waffle? It should be easy for someone else to quickly test the above (i.e. uncomment the code) and just see if waffle builds it.

**Comment by sz-piotr** [comment]
Hey. The error you are seeing comes from ethersjs. You probably are passing an invalid argument to `deployContract`

**Comment by marekkirejczyk** [comment]
Closing, please reopen if still issue still exists.
