### ISSUE TITLE
Use with typechain

### ISSUE THREAD

**Issue by rhlsthrm** [EthWorks/Waffle#146]
I am trying to use Waffle with Typechain. I get the following error when I try to cast a Waffle deployed contract as a generated type:

My relevant test code:
```ts
import { deployContract, getWallets, solidity } from "ethereum-waffle";

describe("Sparkle contract", function() {
  beforeEach(async () => {
    trojanToken = await deployContract(wallet, TrojanTokenArtifact); // type error here
    await trojanToken.functions.setTrojanPool(trojanPool.address);
  })
  ...
})
```

Type error
```
Type 'Contract' is not assignable to type 'TrojanToken'.
  Types of property 'interface' are incompatible.
    Type 'Interface' is not assignable to type 'TrojanTokenInterface'.
      Types of property 'functions' are incompatible.
        Type '{ [name: string]: _FunctionDescription; }' is missing the following properties from type '{ approve: TypedFunctionDescription<{ encode([spender, value]: [string, BigNumberish]): string; }>; transferFrom: TypedFunctionDescription<{ encode([from, to, value]: [string, string, BigNumberish]): string; }>; ... 5 more ...; sellSparkle: TypedFunctionDescription<...>; }': approve, transferFrom, increaseAllowance, decreaseAllowance, and 4 more
```

If I `ts-ignore` the line, everything works properly

**Comment by sz-piotr** [comment]
Typechain integration would be a nice-to-have but it is not a priority right now. We will gladly accept a PR that resolves this issue :)

**Comment by pcowgill** [comment]
This issue is resolved with the latest versions of Waffle, TypeChain, and Buidler (with the relevant Buidler plugins)

No typing problems in this project https://github.com/chicago-ethereum/quadratic-funding/tree/master/contract-project

**Comment by PaulRBerg** [comment]
@pcowgill is correct.

For the record, here's how you can use Waffle's `deployContract` with Typechain:

```ts
import { deployContract } from "ethereum-waffle";
import CounterArtifact from "../artifacts/Counter.json";
import { Counter } from "../typechain/Counter";

const counter = (await deployContract(wallet, CounterArtifact)) as Counter;
```

Where:

+ `signers[0]` is either an instance of `Signer` cast to `Wallet` or an actual instance of `Wallet. You can get the accounts either from Ethers `ethers.getSigners()` or Waffle `waffleProvider.getWallets`
+ `CounterArtifact` is the file resulted after compiling the contract with Waffle/ Buidler/ etc.
+ `Counter` is the file generated by Typechain
