### ISSUE TITLE
Istanbul Support

### ISSUE THREAD

**Issue by NoahZinsmeister** [EthWorks/Waffle#154]
Hi! In anticipation of the upcoming Istanbul hardfork, it would be very helpful to be able to test out the new opcodes, etc.

`ganache-core` already [added support](https://github.com/trufflesuite/ganache-core/releases/tag/v2.9.0-istanbul.0), so it seems all you would have to do is bump the version in your package.json. How feasible is this?

**Comment by NoahZinsmeister** [comment]
hey @sz-piotr / other maintainers, [istanbul is live on rinkeby](https://twitter.com/peter_szilagyi/status/1194685316629700609?s=20), and the mainnet launch is <1 month away. is there a timeline for this ^ feature?

**Comment by sz-piotr** [comment]
We are actively working on it.

**Comment by sz-piotr** [comment]
The relevant code has been merged to master in #158. A new version of waffle will follow soon!

**Comment by NoahZinsmeister** [comment]
amazing, thanks so much @sz-piotr !

**Comment by NoahZinsmeister** [comment]
any idea when this will hit npm?

**Comment by marekkirejczyk** [comment]
Released with [2.1.1](https://github.com/EthWorks/Waffle/releases/tag/2.1.1)

**Comment by NoahZinsmeister** [comment]
i tried that version and it still didn't work (`Hardfork istanbul not set as supported in supportedHardforks`). 2.1.1 is still using ganache-core 2.8.0 whereas istanbul support landed in 2.9.0-istanbul.0.

should i open another issue?

**Comment by NoahZinsmeister** [comment]
i'm still getting the same errors in 2.1.1: `Hardfork istanbul not set as supported in supportedHardforks`. 2.1.1 still relies on a ganache-core version that doesn't have istanbul support as far as i can tell. should i open another issue?

**Comment by marekkirejczyk** [comment]
Reopen, I think the problem is related to ganache no fully supporting Istanbul https://github.com/trufflesuite/ganache-cli/issues/701

**Comment by NoahZinsmeister** [comment]
i'm not sure i understand, i literally think it's because the ganache version isn't `2.9.0-istanbul.0`

**Comment by marekkirejczyk** [comment]
Got it. Its looks like beta version thou, not sure if we should use it.
@sz-piotr @NoahZinsmeister 
What do you think?

**Comment by NoahZinsmeister** [comment]
one solution would be to publish a release with that dependency under a `beta` or `istanbul` tag on npm

**Comment by marekkirejczyk** [comment]
Excellent idea sir!
[2.3.0-istanbul.0](https://github.com/EthWorks/Waffle/releases/tag/2.3.0-istanbul.0) released.

Close if works, comment if not.

**Comment by NoahZinsmeister** [comment]
fyi that was published under the `latest` tag, but it works for me! thanks :)

**Comment by Amxx** [comment]
I'm using 2.3.0-istanbul.0 with

```
"compilerOptions":
{
	"evmVersion": "istanbul"
}
```
But I'm still getting the TypeError:
```
The "chainid" instruction is only available for Istanbul-compatible VMs  (you are currently compiling for "petersburg"
```

How to enable istanbul ?

**Comment by NoahZinsmeister** [comment]
@Amxx you have to add:

```
{
  ...
  "compilerOptions": {
    "evmVersion": "istanbul",
    ...,
  },
  ...
}
```

to your waffle.json (and make sure you're using an istanbul-compatible version of solidity).
