### ISSUE TITLE
ethers v5 support

### ISSUE THREAD

**Issue by pcowgill** [EthWorks/Waffle#162]
I see in [the docs](https://ethereum-waffle.readthedocs.io/en/latest/) that ethers v4 is supported in `ethereum-waffle` 2.x.

With [ethers v5 ready to use for new projects](https://github.com/ethers-io/ethers.js/pull/621), I thought it would be good to kick off this conversation here.

**Comment by marekkirejczyk** [comment]
I didn't see a stable release yet:
https://www.npmjs.com/package/ethers

Do you know when it is planned for?

**Comment by pcowgill** [comment]
@marekkirejczyk I know @ricmoo has been recommending on Twitter that people start using it. He's just working on the changelog and docs still. You're right that there isn't an official "stable" release yet, but `v5` is more or less stable at this point.

Here is the v5 branch: https://github.com/ethers-io/ethers.js/tree/ethers-v5-beta

And here are the work-in-progress docs: https://docs-beta.ethers.io/

**Comment by ricmoo** [comment]
I’m aiming for mid-February for the stable of v5. There are just a few small things left and most of the work left is in the documentation.

It would be great getting a little feedback on v5 if you have any problems integrating it. I’ve been using it for my own personal projects in production for over half a year. :)

**Comment by ricmoo** [comment]
Oh, and the [CHANGELOG](https://github.com/ethers-io/ethers.js/blob/ethers-v5-beta/CHANGELOG.md).

The docs will also include a full table mapping old function names to new; most things haven’t changed and the things that have should allow you to remove boilerplate-ish code. :)

**Comment by pcowgill** [comment]
@marekkirejczyk Any thoughts on what timeframe would make sense for this based on what @ricmoo had to say? Thanks!

**Comment by marekkirejczyk** [comment]
CC @sz-piotr

**Comment by marekkirejczyk** [comment]
I think we should put high pio on it. There is Websocket support coming finally.

**Comment by sz-piotr** [comment]
The biggest blocker is I don't know how to simultaneously support ethers 4 and 5.

**Comment by pcowgill** [comment]
Maybe the simplest strategy is questioning the assumption that supporting them both at once is needed. What use case are you imagining where a user might want to choose between the two?

Or do you mean from a development perspective? I think if all the associated changes will involve lots of PRs, you could make a new ethers-v5 branch off of develop now and start opening PRs against that, and wait until it’s farther along to take develop at that later time into an ethers-v4 branch and merge ethers-v5 into develop.

**Comment by marekkirejczyk** [comment]
Yeah, I guess we should just make it a breaking change and release Waffle 3.0 along with new ethers support

**Comment by pcowgill** [comment]
> Yeah, I guess we should just make it a breaking change and release Waffle 3.0 along with new ethers support

@marekkirejczyk The buidler team just had to make similar decision with ethers v5, and their changes just shipped. Their choice about how to handle this might be useful to look at?

**Comment by marekkirejczyk** [comment]
Didn't look at that yet, but we want to ship Waffle 3.0 in May.

**Comment by pedrouid** [comment]
hey guys, I actually migrated Buidler to ethers v5 to unblock me from my work 😅 

But now Im realizing that I need Waffle to migrate too. How can I help with this? I'm happy to do the same migration 

I'm confused however about this monorepo? This doesn't use Lerna, is this using Yarn workspaces?

**Comment by pedrouid** [comment]
Nevermind I just realized you can just bootstrap the whole monorepo running `yarn` which is pretty awesome 👌 I wish they would support hoisting

**Comment by ricmoo** [comment]
Hoping to get v5 ethers out in May too. The only hold up is the new documentation, which is coming along and should be ready soon(tm).

**Comment by pedrouid** [comment]
Hey @ricmoo, what would be the best way to reach you? Keybase, Telegram, Discord?

**Comment by ricmoo** [comment]
Email prolly works the best, me@ricmoo.com. :)

I do have the others, but I don’t pay much attention to them. Of those, telegram (`@RicMoo`) is prolly the least-worst.

**Comment by pedrouid** [comment]
Alright, I've submitted a PR where it can it succeeds to build and linting but still failling some test regarding `solc` which I'm not sure if it's related to my machine.
Could you review #237? @marekkirejczyk

**Comment by marekkirejczyk** [comment]
Ha Ha, nice job! 
Will try to review, this weekend.

@sz-piotr Perhaps we push it to a branch and release as beta?

**Comment by pedrouid** [comment]
I’d love that 👌 it would be unblock it in my side

**Comment by pedrouid** [comment]
After taking a deeper look, there are no integration tests failing, all the tests that are failing are from the chai helpers. I'd love your help @sz-piotr to debug it

**Comment by pedrouid** [comment]
Any updates on this? @marekkirejczyk @sz-piotr

**Comment by gitpusha** [comment]
> After taking a deeper look, there are no integration tests failing, all the tests that are failing are from the `@ethereum-waffle/chai` matchers. I'd love your help @sz-piotr to debug it

Hi @pedrouid . Same for me. I just upgrade our buidler repo to 
```
    "@nomiclabs/buidler-ethers": "2.0.0-alpha.0",
    "@nomiclabs/buidler-waffle": "2.0.0-alpha.0",
```

in order to play with `"ethers": "5.0.0-beta.184"`.

The only tests that seem to be failing are ones that use matchers like `to.emit(contract, "myEvent")`. 

I assume this is because of the way `ethers v5` handles events on the contract interface. They are now only ordered by their `signature` and split into their own fragments. 

May I ask, did you already find a way to get this matcher to work with `ethers v5` ?

**Comment by pedrouid** [comment]
It will be merged and published soon on Buidler under the beta tag


https://github.com/nomiclabs/buidler/pull/546
