### ISSUE TITLE
Cleanup published package

### ISSUE THREAD

**Issue by krzkaczor** [EthWorks/Waffle#164]
Probably you don't want to include .vscode and original ts files in a published package. 

I highly recommend using `package.json`'s `files` instead of `.npmignore`.

**Comment by krzkaczor** [comment]
One more thing: you explicitly target node 10 (in package.json) yet transpired code targets some ancient architecture (es5?) making code slower and harder to read (I often read transpiled output while debugging).

**Comment by sz-piotr** [comment]
This is a valid point. We should update the build scripts to address that
