### ISSUE TITLE
README on npm needs clarification 

### ISSUE THREAD

**Issue by pcowgill** [EthWorks/Waffle#185]
In the README for `ethereum-waffle` on npm, it references at a method `contractWithWallet` with no context on where it comes from

```js
const tokenFromOtherWallet = contractWithWallet(token, walletTo);
```

**Comment by pcowgill** [comment]
It looks like this is the new approach that can be documented on npm instead

https://github.com/EthWorks/Waffle/commit/d84ecc54089c46567cdee3b04bd49e03e1decf71#diff-04c6e90faac2675aa89e2176d2eec7d8R109

**Comment by sz-piotr** [comment]
The recent readme does not mention `contractWithWallet`
https://www.npmjs.com/package/ethereum-waffle

**Comment by pcowgill** [comment]
Good. Then a change must have been published since when I created this issue. Closing this.
