### ISSUE TITLE
Unnecessary async

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#19]
In `getWallets` the `async` keyword is unnecessary.
https://github.com/EthWorks/Waffle/blob/ae99bd4b4569e0afe1dc22d5cf99e3a0150e26de/lib/waffle.js#L14

**Comment by marekkirejczyk** [comment]
We will keep it for now for backward and potentially future compatibility. Will re-consider a change in Waffle 2.0

**Comment by sz-piotr** [comment]
Since waffle 2.0 is coming out this breaking change can be implemented :)
