### ISSUE TITLE
vyper support

### ISSUE THREAD

**Issue by paulperegud** [EthWorks/Waffle#206]
Does Waffle support contracts written in Vyper? If no, what would it take to add such support?

**Comment by sz-piotr** [comment]
Currently waffle only supports compiling solidity contracts. In order to add vyper support a new sub-package would have to be created, similar to @ethereum-waffle/compiler that deals with vyper and then the cli would have to be able to decide which compiler to use based on the config file

**Comment by hal909** [comment]
+1 For this. It would be amazing to have vyper support for waffle!

**Comment by marekkirejczyk** [comment]
Experimental support for Vyper released in [2.5.0](https://github.com/EthWorks/Waffle/releases/tag/2.5.0).
