### ISSUE TITLE
npx waffle fails

### ISSUE THREAD

**Issue by nventuro** [EthWorks/Waffle#21]
Hey there, thanks for working on this, it looks great!

I'm attempting to try it out, but get errors when running `npx waffle` to compile. I installed `waffle` and `ethers` using NPM, and got the following error:

>Cannot find module 'ganache-core'

After running `npm install ganache-core`, I now get the following error:

>Waffle.compile is not a function

Any pointers?

**Comment by kybernetikos** [comment]
Simpler problem here: I get
`Cannot find module 'babel-runtime/helpers/toConsumableArray'`

**Comment by marekkirejczyk** [comment]
> Waffle.compile is not a function

@nventuro 
This should be fixed now, when you install the newest version.
Let me know if it works.

> Cannot find module 'babel-runtime/helpers/toConsumableArray'

@kybernetikos
Try:
`npm install babel-runtime --save`

**Comment by nventuro** [comment]
That fixed it @marekkirejczyk, thanks. However I found the compilation step to be too slow (48s against truffle's 20s) for it to be useful to me.
