### ISSUE TITLE
Feature Request: make changeBalance and changeBalances factor in gasCost and work with ethers contracts

### ISSUE THREAD

**Issue by gitpusha** [EthWorks/Waffle#211]
Hi,

I just wanted to drop this idea I had while playing with waffle today. I am sure you already had the same ideas:

Regarding the change balance [matchers](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#change-balance), it would be so sweet if:

- They would automatically factor in the gasCost the wallet that sends the tx incurs.

- They also took an `ethers.Contract` instance to monitor balance changes (not just wallets).

**Comment by sz-piotr** [comment]
I looked into the code and it seems weird that it doesn't factor in the gas costs. This might be a bug.

As for supporting `ethers.Contract`: great idea, and it should be relatively easy to implement :)

**Comment by gitpusha** [comment]
Thank you very much @sz-piotr !

> I looked into the code and it seems weird that it doesn't factor in the gas costs. This might be a bug.

So do you mean that there might be a bug in the waffle code that you found? Otherwise I would rather double-check on my end again. Since my balance matcher tests failed with what looked like could be attributed to gas costs, I assumed waffle simply didnt factor them in. But if you say you already do factor them in, I wanna make sure I am not reporting a wrong bug.

**Comment by Robsonsjre** [comment]
I had the same issue using waffle 3.0.0 (not taking gasCost in consideration)

**Comment by gitpusha** [comment]
Hi @sz-piotr - are there any planned updates on this?

**Comment by gitpusha** [comment]
Hi @sz-piotr and @marekkirejczyk - it would be great to get an update on this.

I still get errors like this when using Waffle `3.0.2`:

**Comment by marekkirejczyk** [comment]
A quick workaround is to use `{gasPrice: 0}` as transactions overrides.

**Comment by marekkirejczyk** [comment]
Adding supporting contracts to backlog

**Comment by marekkirejczyk** [comment]
Contract type suppoert added to `changeBalance(s)` added in #363
To be released in 3.1.1
