### ISSUE TITLE
Use "getWallets" with a different provider

### ISSUE THREAD

**Issue by PaulRBerg** [EthWorks/Waffle#270]
I was following Rahul Sethuram's [article](https://hackernoon.com/the-new-solidity-dev-stack-buidler-ethers-waffle-typescript-706830w0) on how to set up a dev environment with Buidler, TypeScript, Ethers and Waffle, but it seems his code is not working anymore because "getWallets" is deprecated in ethereum-waffle@2.5.0.

My understanding is that "getWallets" is part of the "MockProvider" class now, so I can do this:

```ts
new MockProvider().getWallets();
```

And be provided with some dummy wallets. However, I'm interested in getting the wallets of an external provider, to be specific the one exported by Buidler, so I can see Buidler's stack traces.

Is there an alternative for the former "getWallets" function that accepted a provider as an argument?

**Comment by sz-piotr** [comment]
Looks like the alternative is: https://buidler.dev/guides/waffle-testing.html
```ts
const [owner, addr1] = await ethers.getSigners();
```

**Comment by PaulRBerg** [comment]
Thanks @sz-piotr, that works, but unfortunately the "deployContract" function imported from ethereum-waffle expects a "Wallet" not a "Signer":

<img width="910" alt="Capture d’écran 2020-05-20 à 15 13 31" src="https://user-images.githubusercontent.com/8782666/82444896-93074100-9aac-11ea-894c-6f9bc082c519.png">

Do you happen to know how to fix this?

**Comment by PaulRBerg** [comment]
**Update**: nevermind, it seems that the recommended way to do it now is by using the "deploy" method of a contract instance:

```ts
const greeter = await Greeter.deploy("Hello, world!");
```

**Comment by PaulRBerg** [comment]
**Update 3**: I eventually sorted by casting the Signer object to Wallets, so that it's accepted by the "deployContract" method. I'm new to TypeScript and this wasn't obvious to me, but this is how you can do it:

```ts
let signers: Signer[];
let greeter: Greeter;

beforeEach(async () => {
  signers = await ethers.signers();
  greeter = (await deployContract(signers[0] as Wallet, GreeterArtifact, ["Hello, world!"])) as Greeter;
});
```

The `signers[0] as Wallet` part is what I was looking for. Problem sorted!
