### ISSUE TITLE
Jest support

### ISSUE THREAD

**Issue by adrianmcli** [EthWorks/Waffle#275]
We should talk about using Waffle with Jest.

In #89, it was discussed that maybe we can import only the matchers from Waffle to be used. What else needs to be done so that Jest users can easily integrate and use Waffle?

Jest is by far the most popular test runner in the JS space (and has been for a while), far exceeding Mocha and Chai:

![jest](https://user-images.githubusercontent.com/943555/82664826-94498280-9c00-11ea-9e9b-7b08811d0df0.png)

Source: https://npmcharts.com/compare/mocha,jest,chai

**Comment by sz-piotr** [comment]
Currently the chai matchers are exposed as a standalone package called `@ethereum-waffle/chai`. There could be another package called `@ethereum-waffle/jest` that includes jest compatible matchers.

We would welcome a PR, but currently this is not on the roadmap.

**Comment by adrianmcli** [comment]
@sz-piotr Would love to work on a PR, I'll take a look at working on this.

**Comment by adrianmcli** [comment]
Using this issue to save my research:

- https://jestjs.io/docs/en/expect#expectextendmatchers
- https://everyday.codes/javascript/create-custom-jest-matchers-to-test-like-a-pro/
- https://noriste.github.io/reactjsday-2019-testing-course/book/jest-101/custom-matchers.html
- https://github.com/testing-library/jest-dom

**Comment by adrianmcli** [comment]
Human-readable list of matchers to support (plus explanations of what they do):

https://ethereum-waffle.readthedocs.io/en/latest/matchers.html

**Comment by adrianmcli** [comment]
As of now, I think I'm going to create a separate repo for what I want to do (allows me to move a bit faster). If it makes sense, in the future, I would be happy to merge my project into Waffle as I will be making Waffle-inspired Jest watchers.

**Comment by adrianmcli** [comment]
I've created #321 which is ready for preliminary review. It is feature-complete with respect to the existing Chai matchers.
