### ISSUE TITLE
Install fails on Node 9

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#28]
https://travis-ci.com/EthWorks/Doppelganger/builds/94242687

```
error get-caller-file@2.0.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*".
```

**Comment by marekkirejczyk** [comment]
Starting with 2.0 we will no longer support node older than 10.

Requirements in `engine` section of `package.json` are now updated:
https://github.com/EthWorks/Waffle/blob/master/package.json#L23
