### ISSUE TITLE
@ethereum-waffle/provider breaks source maps

### ISSUE THREAD

**Issue by alcuadrado** [EthWorks/Waffle#281]
Hey 👋

I've received lots of complaints about Buidler lines numbers being off. 

I took some time to debug it, and the root of the problem is that `@ethereum-waffle/chai` loads `@ethereum-waffle/provider`, which in turn loads `ganache-core` and breaks the source maps.

I think I can work around this in Buidler, but I'm not sure how to fix it in Waffle v2.

BW, I think this shows how important my proposal #254 is.

**Comment by alcuadrado** [comment]
I do recommend moving [this `import`](https://github.com/EthWorks/Waffle/blob/master/waffle-provider/src/MockProvider.ts#L4) into [`MockProvider`'s `constructor`](https://github.com/EthWorks/Waffle/blob/master/waffle-provider/src/MockProvider.ts#L14). Doing that would fix this problem for users of Waffle that aren't using the `MockProvider`.

**Comment by sz-piotr** [comment]
Interesting. I was wondering what was causing those incorrect line numbers. Gotta extend our eternal love to ganache that has side effects on import. I'll consider moving the import, but as you said it only fixes part of the problem.

**Comment by krzkaczor** [comment]
This is still an issue. Could you repoen? Releated HH issue: https://github.com/nomiclabs/hardhat/issues/1336

It seems like patches (from patch-package) are not included in npm bundle. I will investigate it further and create PR to fix soon.
