### ISSUE TITLE
Add function signature lookup to Mock Contracts

### ISSUE THREAD

**Issue by asselstine** [EthWorks/Waffle#289]
The new mock contracts feature is excellent.  However, I've encountered a roadblock:

The mock functions are keyed only on the function name, so if there are multiple functions with the same name only one is available.

This is ideal in most situations, but it would be great if we could also key on the full function signature (like ethers).   For example:

```
await token.mock.mint.withArgs(user1, 10000)
// can be 
await token.mock['mint(address,uint256)'].withArgs(user1, 10000)
```

This would be a very small and beneficial change.

**Comment by marekkirejczyk** [comment]
Released in Beta 3.0.0-beta.3, looking forward to your feedback.
