### ISSUE TITLE
Does this retrieve error messages from reverts?

### ISSUE THREAD

**Issue by snario** [EthWorks/Waffle#29]
I haven't dug into the details but when I converted some contracts to using this I received several errors of the kind "Invalid JUMP at ..." etc and no errors with revert messages.

**Comment by marekkirejczyk** [comment]
That is a bit weird, would you share the source code?

**Comment by marekkirejczyk** [comment]
Is it still the case?

**Comment by snario** [comment]
This issue has stopped happening without any changes on my end

**Comment by marekkirejczyk** [comment]
Closing

**Comment by marekkirejczyk** [comment]
Closing then.
