### ISSUE TITLE
How to change the msg.sender in tests?

### ISSUE THREAD

**Issue by PaulRBerg** [EthWorks/Waffle#304]
Truffle has a "from" field among its overridable config when calling a TruffleContract. Is there an equivalent field when interacting with a Waffle/ Ethers contract?

I couldn't find any information about this in the [docs](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html).

**Comment by marekkirejczyk** [comment]
You can use ethers.js feature. There is a `connect ( signer ) ` method on cotnract.
https://docs.ethers.io/ethers.js/html/api-contract.html#id1

**Comment by PaulRBerg** [comment]
Thank you, @marekkirejczyk!
