### ISSUE TITLE
Feature request: use "Signer" instead of "Wallet"

### ISSUE THREAD

**Issue by PaulRBerg** [EthWorks/Waffle#308]
Richard's comments from this thread: https://github.com/ethers-io/ethers.js/issues/263

> Waffle should certainly not be using Wallet as their low-level Signer as Wallet is a fairly high-level Signer. The Signer sub-class should be what they use, since a Wallet requires a private key, which many situations do not have access to.

As explained there, I encountered multiple bottlenecks while joggling with Ethers and Waffle in my testing environment, one of them being another issue I opened two weeks ago: https://github.com/EthWorks/Waffle/issues/270

Refactoring Waffle to use the `Signer` class would iron out most interoperability issues.

**Comment by marekkirejczyk** [comment]
Will implement soon

**Comment by marekkirejczyk** [comment]
Released in Beta 3.0.0-beta.3, looking forward to your feedback.

**Comment by PaulRBerg** [comment]
Sorry for the delay - just got the chance to make the refactor and it works great.

It's in our codebase since commit [3aaebb](https://github.com/MainframeHQ/mainframe-lending-protocol/commit/3aaebb29d6cc19dca249193535998d7429d404bc).
