### ISSUE TITLE
Linking does not work on beta 2

### ISSUE THREAD

**Issue by snario** [EthWorks/Waffle#33]
Seems like the way that links are referenced has changed to look like this:

**`build/AppRegistry.json`**:
```
  610     "assembly": "    /* \"contracts/AppRegistry.sol\":358:525  contract AppRegistry
  611     "bytecode": {
  612       "linkReferences": {
  613         "contracts/libs/LibStaticCall.sol": {
  614           "LibStaticCall": [
  615             {
  616               "length": 20,
  617               "start": 5221
  618             },
  619             {
  620               "length": 20,
  621               "start": 6257
  622             },
  623             {
  624               "length": 20,
  625               "start": 6733
  626             },
  627             {
  628               "length": 20,
  629               "start": 7119
  630             }
  631           ]
  632         }
  633       },
  634       "object": "608060405234801561001057600080fd5b50614089806100206 ...
  635   
```

So this logic doesn't work anymore I don't think:

https://github.com/EthWorks/Waffle/blob/111bccd2740d06d4a74ef1e005853b18a927f1e3/lib/waffle.js#L41-L44

Haven't fully tested yet.

**Comment by marekkirejczyk** [comment]
ahhh yes.... This was modified for solidity 5.0 that returns data in a different format. My bad. Will add support for both soon.

**Comment by marekkirejczyk** [comment]
Should be fixed with [#32](https://github.com/EthWorks/Waffle/pull/32).
Published in `ethereum-waffle@2.0.0-beta.5`.

Also added integration tests that iterate through different configurations (solidity versions and compilers), so that we can discover this kind of regressions early in the future.

Let me know if now works.

**Comment by snario** [comment]
@marekkirejczyk 

Your test seems to use the right value for `libraryName` the compiler uses:

https://github.com/EthWorks/Waffle/blob/2cfb47eb82a0dbc00c5c283fcad115d48093f2db/test/compiler/integration.js#L71

But it does not seem to be used in the actual implementation:

https://github.com/EthWorks/Waffle/blob/2cfb47eb82a0dbc00c5c283fcad115d48093f2db/lib/link.js#L13

where `libraryName` is just the name of the contract, not the fully qualified name

**Comment by snario** [comment]
Oh I suppose it's the user of the library's job to input the correct value... I see. Maybe a good feature to add would be to auto-detect the fully qualified name.

**Comment by marekkirejczyk** [comment]
Yes, that is why i updated readme, to make sure one will provide fully qualified name.
```js
link(LibraryConsumer, 'path/to/file:MyLibrary.sol:MyLibrary', myLibrary.address);
```

In general, there are two problems with auto-detecting fully qualified names:
1) How do we solve collisions?
2) `link` function would need access to compilation data, which seems like overhead to me.

The easiest thing to do would be to simplify fully qualified names, but I don't have an idea how it could work.

**Comment by fredfortier** [comment]
This page shows a slash instead of a column before the library name: https://ethereum-waffle.readthedocs.io/en/latest/features.html?highlight=link
