### ISSUE TITLE
Breaking change with fixture and Signers

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#332]
After #330 was released old fixtures no longer work, because the change was not backwards compatible. Example:
```ts
async function myFixture (wallets: Wallet[], provider: MockProvider) {
  // do stuff
}

loadFixture(myFixture)
```
In new waffle versions this is an error because loadFixture expects a function that receives Signers.

@alcuadrado We can keep the change in chai matchers but we will probably have to revert this for fixtures. Thoughts?

**Comment by alcuadrado** [comment]
Ouch, sorry about this. I don't understand how it happened. I guess it has to do with how TS manages type variances wet arrays.

I agree that this should be reverted.

**Comment by PaulRBerg** [comment]
Would an interim solution be to cast the Signer array as Wallets? (Although this is [not recommended](https://github.com/ethers-io/ethers.js/issues/263#issuecomment-639996802)).
