### ISSUE TITLE
Should I Deploy Contracts to a Test Network using Waffle?

### ISSUE THREAD

**Issue by mudgen** [EthWorks/Waffle#341]
I see that Waffle is for writing, compiling and testing smart contracts.  Should I also use it for deploying my contracts to a test network or should I use something like Truffle for deployment?

**Comment by PaulRBerg** [comment]
No, Waffle doesn't do deployments. I recommend reading Rahul Sethuram's [The New Solidity Dev Stack: Buidler + Ethers + Waffle + Typescript](https://medium.com/@rahulsethuram/the-new-solidity-dev-stack-buidler-ethers-waffle-typescript-tutorial-f07917de48ae).

Alternatively, you can check out my [solidity-template](https://github.com/paulrberg/solidity-template), which integrates Buidler, Waffle and TypeChain too.

**Comment by mudgen** [comment]
@PaulRBerg Thank you, I appreciate the answer.

**Comment by marekkirejczyk** [comment]
Closing :)
