### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by krzkaczor** [EthWorks/Waffle#343]
Hey!

Small feedback regarding docs, leave it or take it ;)

1. IMO, header on https://getwaffle.io/ misses link to the documentation (next `View on Github`). User need to scroll all the way down to find the link.
2. Personally I hate Read the docs ;) but since you use it already, have you considered uncollapsing menu items so it's easy to see whats inside a given page without entering it first? (idk if it's even easy to achieve with RTD)
3. The [deployment section](https://ethereum-waffle.readthedocs.io/en/latest/basic-testing.html#deploying-contracts) could use some full-example. Like setup ganache, and then create deployment script creating provider etc. How to deploy on kovan etc. It's easy stuff but having some place to copy code from could be useful.

**Comment by marekkirejczyk** [comment]
Ad 1. Agree - will add a button (have it in backlog)
Ad 2. We researched several, and decided to stay with Read the doc. None is perfect, RTD is bearable
Ad 3. Waffle is intended for testing, not a development, for wider functionality look at [buidler](https://buidler.dev/) (with Waffle as testing framework ofc)

**Comment by marekkirejczyk** [comment]
Ad 1. Added.
