### ISSUE TITLE
Feature request: pass custom arguments to fixtures

### ISSUE THREAD

**Issue by PaulRBerg** [EthWorks/Waffle#345]
Using fixtures is easy for basic contracts, but what about contracts that need the address of a previously-deployed contract as part of its constructor arguments?

The `Fixture` type doesn't seem to allow any other arguments except for "signers" and "provider":

https://github.com/EthWorks/Waffle/blob/3.0.2/waffle-provider/src/fixtures.ts#L4

**Comment by PaulRBerg** [comment]
I read about [mock contracts](https://ethereum-waffle.readthedocs.io/en/latest/mock-contract.html) in the meantime and I think I found an alternative solution to my problem.

I can avoid having to pass custom arguments to my fixtures by mocking the contract dependencies of a contract. I will rewrite this:

```ts
  const yToken: YToken = ((await deployContract(signers[0], YTokenArtifact, [
    "DAI/ETH (2021-01-01)",
    "yDAI-JAN21",
    18,
    fintroller.address,
    underlying.address,
    collateral.address,
    guarantorPool.address,
    BigNumber.from(1609459199),
  ])) as unknown) as YToken;
```

To this:

```ts
  const fintrollerMock: MockContract = deployMockContract(signers[0], FintrollerAbi);
  const underlyingMock: MockContract = deployMockContract(signers[0], Erc20Abi);
  const collateralMock: MockContract = deployMockContract(signers[0], Erc20Abi);
  const guarantorPoolMock: MockContract = deployMockContract(signers[0], GuarantorPoolAbi);
  const yToken: YToken = ((await deployContract(signers[0], YTokenArtifact, [
    "DAI/ETH (2021-01-01)",
    "yDAI-JAN21",
    18,
    fintrollerMock.address,
    underlyingMock.address,
    collateralMock.address,
    guarantorPoolMock.address,
    BigNumber.from(1609459199),
  ])) as unknown) as YToken;
```

**Comment by marekkirejczyk** [comment]
How about higher level function, e.g.:
```ts
  const fixture = (yourArgs) => async ([wallet, other], provider) => {
    const token = await deployContract(wallet, BasicTokenMock, [
      yourArgs.address, 1000
    ]);
    return {token, wallet, other};
  }
```

**Comment by PaulRBerg** [comment]
Aah.. this should work too. Thanks!

Not sure if I should close this issue though, custom arguments could still be added to fixtures themselves?

**Comment by marekkirejczyk** [comment]
Let's close it. If language allows to do something, than we should not extend framework. We try to keep it small and concise.
