### ISSUE TITLE
Expose server functionality

### ISSUE THREAD

**Issue by lastmjs** [EthWorks/Waffle#348]
Hey! Great tool! I'm really enjoying it so far.

One use case that it doesn't easily support, though I have found a workaround, is creating a local development server. Essentially, what I would like is to be able to create a ganache server just as easily as I can create a MockProvider. Right now I have to manually create the server using ganache, and then create a jsonrpc provider with ethers, pull off some signers, and deploy my contracts. Then my frontend running on localhost can interact with my code.

I would like it to be just as easy to run automated tests on my contracts with Waffle as it is to interact with my contracts over http on Waffle. Right now it requires a small workaround.

Here's what I'm doing to create the server:

```typescript
import ganache from 'ganache-core';
import { deployContracts } from '../utilities/utilities';
import {
    ethers,
    Wallet
} from 'ethers';

const server = ganache.server({
    gasLimit: 12000000,
    accounts: [
        {
            secretKey: '0x29f3edee0ad3abf8e2699402e0e28cd6492c9be7eaab00d732a791c33552f797',
            balance: '1000000000000000000'
        },
        {
            secretKey: '0x5c8b9227cd5065c7e3f6b73826b8b42e198c4497f6688e3085d5ab3a6d520e74',
            balance: '1000000000000000000'
        }
    ]
});

server.listen(8545, async () => {
    const provider = new ethers.providers.JsonRpcProvider('http://localhost:8545');

    const linkTokenOwner = provider.getSigner(0);
    const proofOfRankOwner = provider.getSigner(1);

    const {
        linkToken,
        proofOfRank
    } = await deployContracts(linkTokenOwner as unknown as Wallet, proofOfRankOwner as unknown as Wallet);

    console.log('ganache listening on port 8545');
});
```
Here's the deployContract function:

```typescript
import {
    deployContract
} from 'ethereum-waffle';
import {
    Wallet,
    Contract
} from 'ethers';
import ProofOfRank from '../build/ProofOfRank.json';
import LinkToken from '../build/LinkToken.json';

export async function deployContracts(linkOwner: Wallet, proofOfRankOwner: Wallet): Promise<{
    linkToken: Contract,
    proofOfRank: Contract
}> {
    const linkToken: Contract = await deployContract(linkOwner, LinkToken, [], {
        gasLimit: 10000000
    });
    const proofOfRank: Contract = await deployContract(proofOfRankOwner, ProofOfRank, [linkToken.address], {
        gasLimit: 10000000
    });

    return {
        linkToken,
        proofOfRank
    };
}
```

**Comment by marekkirejczyk** [comment]
Hi @lastmjs,

Thanks for the kind words. 

Our focus is solely on testing, if you look for functionalities like you described, checkout [buidler.dev](https://buidler.dev/). It works with Waffle as a recommended option and has development features like you described (and much more)

Closing for now, feel free to reopen if you would like to ad more to the discussion.
