### ISSUE TITLE
parse address from ethers signer

### ISSUE THREAD

**Issue by thegostep** [EthWorks/Waffle#358]
Current
```ts
let user: Signer

it('should get balance and owner', async () => {
  expect(await token.balanceOf(await user.getAddress())).to.eq(0)
  expect(await token.owner()).to.eq(await user.getAddress())
})
```
Desired
```ts
let user: Signer

it('should get balance and owner', async () => {
  expect(await token.balanceOf(user)).to.eq(0)
  expect(await token.owner()).to.eq(user)
})
```
Related to https://github.com/ethers-io/ethers.js/issues/1035

**Comment by marekkirejczyk** [comment]
@thegostep Great idea for nice syntax sugar, however:
- balanceOf is a feature of ethers not Waffle, same as getAddress
- excluding await from the syntax would be somewhat complex if possible at all
- we would like to avoid "magical" features, with methods that takes many different types and do custom actions based of them

Closing for now, feel free to reopen if you would like to add more to the discussion
