### ISSUE TITLE
Mock function without return value

### ISSUE THREAD

**Issue by PaulRBerg** [EthWorks/Waffle#360]
The mocking feature lacks a way to mock a function without returning a specific value from it. I double-checked this in the [Doppelganger.sol](https://github.com/EthWorks/Waffle/blob/3.1.0/waffle-mock-contract/src/Doppelganger.sol) contract before opening the issue.

Here's the scenario I want to test:

- Contract Foo depends on ERC-20 token
- The ERC-20 token is a non-standard ERC-20 contract that [does not return a value on "transfer" and "transferFrom"](https://medium.com/coinmonks/missing-return-value-bug-at-least-130-tokens-affected-d67bf08521ca)

Since Waffle doesn't let me mock functions without returning a specific value like a true or false, the only way for me to test this edge case is by writing an integration test with an actual implementation of non-standard ERC-20.

**Comment by vnavascues** [comment]
@PaulRBerg I'm currently testing a smart contract with your scenario and I'm able to mock functions that do not return (i.e. `approve()` and `safeTransferFrom`).

**ethereum-waffle: 3.1.0**

Contract `DeedRepository.sol` (ERC721):
```solidity
contract DeedRepository is TrustedInitializable, TrustedERC721UpgradeSafe {
...
// approve() and safeTransferFrom() are not overridden here
```

Contract `AuctionRepository.sol` (it calls `DeedRepository.sol`):
```solidity
import {DeedRepository as TrustedDeedRepository} from "./DeedRepository.sol":
...
    function _approveAndSafeTransferFrom(
        address _from,
        address _to,
        address _deedRepositoryAddress,
        uint256 _deedId
    ) private {
        TrustedDeedRepository remoteContract = TrustedDeedRepository(
            _deedRepositoryAddress
        );
        remoteContract.approve(_to, _deedId);
        remoteContract.safeTransferFrom(_from, _to, _deedId);
    }
```

A snippet of one of the many `AuctionRepository` tests where I mock the `_approveAndSafeTransferFrom()` ERC721 method calls (as `safeTransferFrom()` is overloaded and I'm using TypeChain I must pass the function selector):
```typescript
import { MockContract } from "ethereum-waffle";
...
    mockDeedRepository = await deployMockContract(
      this.deployer,
      DeedRepositoryArtifact.abi,
    );
...
      await mockDeedRepository.mock.approve
        .withArgs(ownerAddr, deedId)
        .returns();
      await mockDeedRepository.mock["safeTransferFrom(address,address,uint256)"]
        .withArgs(this.auctionRepository.address, ownerAddr, deedId)
        .returns();
```
I think it is the same pattern you are describing. Hope it helps!

**Comment by PaulRBerg** [comment]
I didn't think about not passing any argument haha!

```ts
.returns();
```

This looks like indeed the solution. Thanks @vnavascues!

**Comment by vnavascues** [comment]
@PaulRBerg a pleasure! Your contributions have helped me a lot.
