### ISSUE TITLE
Multiple SPDX license identifiers found in source file. Use "AND" or "OR" to combine multiple licenses. Please see https://spdx.org for more information.

### ISSUE THREAD

**Issue by myxtype** [EthWorks/Waffle#367]
Multiple SPDX license identifiers found in source file. Use "AND" or "OR" to combine multiple licenses. Please see https://spdx.org for more information.

**Comment by myxtype** [comment]
Flatten Error.

**Comment by marekkirejczyk** [comment]
In Waffle 3.1.1 flatten will work, but show warnning. (Released today)

@vanruch Should we update further to use AND or OR?

**Comment by vanruch** [comment]
@marekkirejczyk I wasn't aware AND/OR keywords are supported. We should totally use AND instead of showing warning
