### ISSUE TITLE
Contract with a Signer cannot override from

### ISSUE THREAD

**Issue by aaronovz1** [EthWorks/Waffle#390]
`Contract with a Signer cannot override from`

What does this error mean and how do I get around it?

This is the test code:
```
const [owner, bob, carol, tom] = provider.getWallets();
...
token = await deployContract(owner, Token, [0]);
...
await token.transfer(carol.address, '100', { from: bob.address }); // fails
```

**Comment by AlbertSu123** [comment]
Hi, I have the same error and I was wondering how you fixed the error.

I'm also trying to call .transfer on an erc 20 token but I have an approve statement before the .transfer() call.

**Comment by aaronovz1** [comment]
Hi,

In waffle you need to use connect()

```
await token.connect(bob).transfer(carol.address, '100');
```
