### ISSUE TITLE
solc ^0.7.2

### ISSUE THREAD

**Issue by seik** [EthWorks/Waffle#394]
Hi, I was trying to use waffle with a project pinned to `0.7.4` but I was getting errors of the compiler not being found. This is fixed in 769cd411254bb150ea4b5581b930ecaad73f0037 but I think there is no way of using this until a new version is released.

Tried to install the repo directly from github but since its a monorepo I can't. Is there any way to use this commit right now? Is there a new release planned?

Thanks.

**Comment by marekkirejczyk** [comment]
Fix released in version [3.2.1](https://github.com/EthWorks/Waffle/releases/tag/3.2.1)
