### ISSUE TITLE
contractWithWallet unnecessary. Ethers has built-in contract.connect.

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#40]
The following function is unnecessary.
```js
export const contractWithWallet = (contract, wallet) =>
  new Contract(contract.address, contract.interface.abi, wallet);
```

Ethers already has this feature built-in:
https://docs.ethers.io/ethers.js/html/api-contract.html?highlight=connect#connecting-to-a-contract
```js
let contractWithSigner = contract.connect(wallet);
```

**Comment by marekkirejczyk** [comment]
Good point. contractWithWallet` is now removed (starting version `2.0.0.beta.11`)
