### ISSUE TITLE
revertedWith succeeds despite only partial match

### ISSUE THREAD

**Issue by thegostep** [EthWorks/Waffle#400]

**Comment by NIC619** [comment]
Empty message string would pass too

**Comment by skywinder** [comment]
Hello, maintainers, **this Error still persist in `3.4.0`**

cc @marekkirejczyk 

False-negative scenario if I remove the beginning or ending part of `reveredWith` parameter!

### True-negative case (original string):

<img width="415" alt="CleanShot 2021-08-19 at 18 13 41@2x" src="https://user-images.githubusercontent.com/3356474/130059369-2df80c9e-0e0b-4b79-a6e4-cf0fc35d1494.png">


### False-negative scenario (it pass, but should fail)

<img width="471" alt="CleanShot 2021-08-19 at 18 13 19@2x" src="https://user-images.githubusercontent.com/3356474/130059396-49dee223-47d1-4ece-ac0a-e883ef376b55.png">

**Comment by rzadp** [comment]
Please see https://github.com/TrueFiEng/Waffle/issues/558#issuecomment-1198266089
