### ISSUE TITLE
Getting Started is missing some typescript related instructions

### ISSUE THREAD

**Issue by jtakalai** [EthWorks/Waffle#407]
Hi,

I followed the excellently written Getting Started instruction, but had to jump a couple hurdles before getting green checkmark from my test:
* instead of `mocha`, you need `ts-mocha` because otherwise it Just Wouldn't Work for me
  * drop-in replacement pretty much though, just replace `mocha` with `ts-mocha`
* `tsconfig.json` is needed, something like https://www.npmjs.com/package/@tsconfig/node12 probably can be just linked to
  * it additionally needs `"resolveJsonModule": true` added though
* `npm install --save-dev @types/mocha @types/chai` is needed in the "Writing tests" part
* probably good idea to add "prerequisites" in the very beginning, stuff like "check that your node.js version is at least 12"

Thanks for a great test framework!

**Comment by platocrat** [comment]
> * instead of `mocha`, you need `ts-mocha` because otherwise it Just Wouldn't Work for me
>   
>   * drop-in replacement pretty much though, just replace `mocha` with `ts-mocha`

These steps helped me out.
Thank you kind ser!! 
Hopefully additional documentation gets added soon.
