### ISSUE TITLE
Support for events emitted in an arbitrary transaction

### ISSUE THREAD

**Issue by ejwessel** [EthWorks/Waffle#418]
Similar to: 
* https://docs.openzeppelin.com/test-helpers/0.5/api#intransaction
* https://github.com/rkalis/truffle-assertions#truffleassertcreatetransactionresultcontract-transactionhash

It would be great to have support for checking events that occur within a transaction hash to assert that certain events are emitted.

Using the current form `await expect(trxRequest).to.emit(emitter, 'Event')` fails with:
```
Error: invalid hash (argument="value", value=undefined, code=INVALID_ARGUMENT, version=providers/5.0.17)
``` 
When attempting to check an event was emitted if a transaction hash is returned instead of a receipt.

potential related issues:
* https://github.com/EthWorks/Waffle/issues/196
* https://github.com/EthWorks/Waffle/issues/119

**Comment by marekkirejczyk** [comment]
Released in [3.2.2](https://github.com/EthWorks/Waffle/releases/tag/3.2.2)
