### ISSUE TITLE
revertedWith matcher doesn't work with messages containing parentheses

### ISSUE THREAD

**Issue by msieczko** [EthWorks/Waffle#425]
This is caused by the use of `String.search()` function in this line:
https://github.com/EthWorks/Waffle/blob/9a921bd6749dd5cac747d2a7ab3552691cc61f5f/waffle-chai/src/matchers/revertedWith.ts#L28
which expects a `regexp` as a parameter.

Related issue: #400

**Comment by NoahMarconi** [comment]
It's more than just parentheses. The following passes regardless of what you put as the string:

https://github.com/NoahMarconi/airdrop-contracts/blob/52ae30d5b0935b34917d607041aebf9b5418497f/test/airdrop.spec.ts#L87-L94

**Comment by marekkirejczyk** [comment]
Fixed and released in 3.3.0
