### ISSUE TITLE
Are migrations supported?

### ISSUE THREAD

**Issue by pavlovdog** [EthWorks/Waffle#430]
Hi guys! Found out about Waffle, looks fantastic! I definitely gonna try it in the following projects. I have read the docs and didn't find any paragraph about migrations, like in Truffle. Are they supported? Something like `waffle migrate`.

Thanks in advance!

**Comment by marekkirejczyk** [comment]
Hi @pavlovdog, 

For smart contract deployment we developed separate tool:
https://github.com/EthWorks/Mars

Soon to be announced.

Marek
