### ISSUE TITLE
deployContract payable eth value only accepts hex strings

### ISSUE THREAD

**Issue by mikec** [EthWorks/Waffle#433]
```
const { deployContract } = require('ethereum-waffle')
await deployContract(
  ...,
  { value: '1000000000000000000' }
)
```

results in this error:

`Error: invalid hexlify value (argument="value", value="1000000000000000000", code=INVALID_ARGUMENT, version=bytes/5.0.10)`

using ethereum-waffle v3.2.2

**Comment by marekkirejczyk** [comment]
Last argument of deployContract is passed to `DeployFactory.deploy()` in ethers and then use as a stub for transaction. If it is string it will try to parse it as hex. However you can pass BigNumber and it should work.

**Comment by marekkirejczyk** [comment]
Closing for now, reopen if it is still an issue.
