### ISSUE TITLE
How to compare two objects with expect() similar ad Truffle?

### ISSUE THREAD

**Issue by ldru** [EthWorks/Waffle#436]
How to compare two objects with expect()  as the following sample as in Truffle?
···
      await expect(call(gov, 'getReceipt', [proposalId, accounts[2]])).resolves.toPartEqual({hasVoted: false});
···

**Comment by ldru** [comment]
Need help on two more questions:
1)  Freeze the block timestamp for testing.
2)  Quick move block number to the specifed value.   
Is there someone kown how to code these two special test requirement?

**Comment by marekkirejczyk** [comment]
You can use mocha `expect(await call(...)).to.deep.include({...});`
