### ISSUE TITLE
Compilation output is different from Truffles compilation output

### ISSUE THREAD

**Issue by snario** [EthWorks/Waffle#48]
This seems to be by design but I am curious why? It might be helpful for adoption to use the same format.

**Comment by marekkirejczyk** [comment]
We are using now default native solidity output format, that is recommended for automated tools. 

This makes it quite troublesome for migrating multicomponent projects to new Waffle version. 

We will support the old format back in the next beta version. I will work on it today.

**Comment by marekkirejczyk** [comment]
I added a legacy output flag to the Waffle configuration file, that will enforce output compatible with old versions and truffle. Available starting with `2.0.0.beta.10`.
```js
{
  ...
  "legacyOutput": "true"
}
```

**Comment by snario** [comment]
@marekkirejczyk I think `deployContract` needs to be able to differentiate between the formats now

**Comment by marekkirejczyk** [comment]
New format produce new fields: `abi` and `contractJSON.evm.bytecode.object`.

Legacy produces both new and old (`abi` and `contractJSON.evm.bytecode.object`) fields (`interface`, `bytecode`). 

Therefore there is no support for legacy.
I guess we could document it better.

**Comment by marekkirejczyk** [comment]
Add some basic info here:
https://ethereum-waffle.readthedocs.io/en/latest/
