### ISSUE TITLE
"closeTo" not working in TypeScript

### ISSUE THREAD

**Issue by paulrberg** [EthWorks/Waffle#512]
## Description

I've recently wanted to try the latest "closeTo" chai matcher (added in #417), but it doesn't seem to be working in TypeScript, or at least not in TypeScript when Waffle is imported via the Hardhat plugin. If it turns out that the culprit is Hardhat, sorry for spamming you!

```
An unexpected error occurred:

error TS2345: Argument of type 'BigNumber' is not assignable to parameter of type 'number'.

           expect(expected).to.be.closeTo(result, EPSILON);
```

This seems to be a type error. The ["closeTo" override](https://github.com/EthWorks/Waffle/blob/90e78f29f296302c702966b856f6d3df89294fe1/waffle-chai/src/matchers/bigNumber.ts#L30) is not recognised in my dev environment.

## Steps to Reproduce

Clone my [solidity-template](https://github.com/paulrberg/solidity-template) and try to write a test that uses "closeTo".

## Environment

- @nomiclabs/hardhat-waffle@2.0.1
- ethereum-waffle@3.3.0
- hardhat@2.2.1

**Comment by paulrberg** [comment]
Ah, I think I figured out why. There are no types for "closeTo" in the `types.ts` file:

https://github.com/EthWorks/Waffle/blob/90e78f29f296302c702966b856f6d3df89294fe1/waffle-chai/src/types.ts

**Comment by ncitron** [comment]
I am also experiencing this issue. I think the types for the function should both be changed to `BigNumber` or `BigNumberish`. Is there a fix inbound?

**Comment by paulrberg** [comment]
@ncitron, as a temporary solution, you could use my custom [near](https://github.com/hifi-finance/prb-math/blob/b6ebdaffaa9cd1bc3bbc859f75de660b15c3bd07/test/shared/assertions.ts) assertion.

**Comment by ncitron** [comment]
Thanks!

**Comment by vanruch** [comment]
@ncitron For some reason I couldn't figure out how to make ethers type work with chai. The rest of assertions use `any` as well. If you have an idea how to improve typings, feel free to submit a PR

**Comment by vanruch** [comment]
Should be fixed in 3.4.0, will close it for now

**Comment by paulrberg** [comment]
I don't think this is solved yet. The expected type for both arguments is `number`, not `BigNumber`. Whereas I think the goal was to enable `closeTo` to work with the latter. The [docs](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html) give this example:

```ts
expect(BigNumber.from(100)).to.be.closeTo(BigNumber.from(101), 10);
```

**Comment by rrodriguezreche** [comment]
`within` isnt working for me either. The example in the documentation is giving errors in typescript. Using ^3.4.0.

![image](https://user-images.githubusercontent.com/46090742/124812744-4e668f80-df64-11eb-93ef-630f68d5ac64.png)

**Comment by 0xGorilla** [comment]
Please reopen this issue, as mention above, `within` isn't working because there are multiple matchers that are not included in `types.ts`

**Comment by karlfarms** [comment]
This really needs to be fixed... 
`near()` from @paulrberg works well but I wanted something that would adapt to any BigNumber 18 d.p and 6 d.p

Here is my solution :

```
// near.ts
// Custom method : being near means being within the expected variance determined by MAX_VARIANCE
import { BigNumber } from '@ethersproject/bignumber'

export {}

const MAX_VARIANCE = 1000 // 0.1 % accepted variance

declare global {
  export namespace Chai {
    interface Assertion {
      near(actual: BigNumber): void
    }
  }
}

function max(x: BigNumber, y: BigNumber): BigNumber {
  return x.gte(y) ? x : y
}

export function near(chai: Chai.ChaiStatic): void {
  const Assertion = chai.Assertion
  Assertion.addMethod('near', function (actual: BigNumber): void {
    const expected = (this._obj as BigNumber).abs()
    const delta: BigNumber = expected.sub(actual.abs()).abs()
    this.assert(
      delta.lte(expected.div(MAX_VARIANCE)),
      'expected #{exp} to be near #{act}',
      'expected #{exp} to not be near #{act}',
      String(expected),
      String(actual)
    )
  })
}
```
Then the test : 

```
// Test.ts
import chai from 'chai'
import { expect } from 'chai'
import { parseEther, parseUnits } from '@ethersproject/units'
import { solidity } from 'ethereum-waffle'
import { near } from './near'

chai.use(solidity)
chai.use(near)

describe('Testing Near Assert', function () {
  it('should detect variance 18 d.p', async function () {
    const a = parseEther('1000')
    const b = parseEther('1001')
    const c = parseEther('999')
    const d = parseEther('1001.1')
    const e = parseEther('998.999999999')

    expect(a).to.be.near(a)
    expect(a).to.be.near(b)
    expect(a).to.be.near(c)
    expect(a).to.be.not.near(d) // not near enough
    expect(a).to.be.not.near(e) // not near enough
  })

  it('should detect variance 6 d.p', async function () {
    const a = parseUnits('1000',6)
    const b = parseUnits('1001',6)
    const c = parseUnits('999',6)
    const d = parseUnits('1001.1',6)
    const e = parseUnits('998.99999',6)

    expect(a).to.be.near(a)
    expect(a).to.be.near(b)
    expect(a).to.be.near(c)
    expect(a).to.be.not.near(d) // not near enough
    expect(a).to.be.not.near(e) // not near enough
  })
})
```

Hopefully this helps someone.
