### ISSUE TITLE
Web3 beta 38 causes the package to stop working

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#69]
## Caused by:
https://github.com/ethereum/web3.js/issues/2221

## Recommended solution for Waffle:
Blacklist web3 beta38 version or just wait for web3 to fix the issue. It is not Waffle's fault.

## Recommended solution for users:
Use yarn and add this to `package.json`
```
"resolutions": {
  "web3": "1.0.0-beta.37"
}
```

**Comment by marekkirejczyk** [comment]
Fixed by #75
