### ISSUE TITLE
Support passing a custom solc path

### ISSUE THREAD

**Issue by snario** [EthWorks/Waffle#78]
Would be nice if I could fix it to a particular path e.g., `../../node_modules/solc/index.js`

**Comment by marekkirejczyk** [comment]
Do you mean solcjs in particular?

**Comment by snario** [comment]
Yes sorry, specifically solcjs

**Comment by snario** [comment]
e.g.,

```
{
  ...,
  "solcVersion": "../../node_modules/solc"
}
```

**Comment by marekkirejczyk** [comment]
Implemented in [2.0.16](https://github.com/EthWorks/Waffle/releases/tag/2.0.16) @snario
