### ISSUE TITLE
deployContract returns null when using Infura nodes

### ISSUE THREAD

**Issue by maxweng** [EthWorks/Waffle#84]
My code works fine with my local dev, until I started to deploy contracts to Rinkeby with Infura nodes. And got errors like `TypeError: Cannot read property 'contractAddress' of null`.

I did a bit research, and found out that someone mentioned that it's because the light clients don't return the receipt for `getTransactionReceipt` call. 

So, I'm wondering if the team knows that or we just have to run a full node to deploy contracts?

**Comment by snario** [comment]
I'm not sure if deployment is in the scope of this package?
