### ISSUE TITLE
Export LinkableContract type

### ISSUE THREAD

**Issue by AlexXiong97** [EthWorks/Waffle#88]
Currently `LinkableContract` type is not exported, yet the `link()` function requires the type of the first parameter to be of that type.

**Comment by marekkirejczyk** [comment]
Hi @AlexXiong97, we are currently snowed under projects, would like to do a PR?

**Comment by AlexXiong97** [comment]
Ah... @marekkirejczyk Sorry I was mistaken. It should work fine, I messed up the order of parameters in the waffle.link func.

**Comment by marekkirejczyk** [comment]
Thanks for update 😄
