### ISSUE TITLE
Import from Node Modules does not work on Windows

### ISSUE THREAD

**Issue by tchataigner** [EthWorks/Waffle#92]
Hello all !

I just saw this package and I wanted to try it out for writing and testing some contracts. 

Because of work reglementations I am forced to develop on a Windows 10 OS. Everything went well until I tried to import the ERC721 from the Open Zepplin Package. 

`import "openzeppelin-solidity/contracts/token/ERC721/ERC721Full.sol";`

When doing so I got this error : 

`Error: Invalid URI "c:/Users/tchataignerprestatai/WebstormProjects/artikodin-contracts/node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Full.sol"`

After looking from where it might come from I found that this test is going on in the package 
`if (!(self.uri.host || (self.uri.hostname && self.uri.port)) && !self.uri.isUnix)` (from request package, request.js line 260)
and its where the code is returning.

Any idea of how to solve that ?

**Comment by yaram** [comment]
I've identified the issue as being in the `@resolver-engine/core` package. I've submitted an issue here Crypto-Punkers/resolver-engine#182

**Comment by yaram** [comment]
This issue has been fixed in Crypto-Punkers/resolver-engine#184
