### ISSUE TITLE
`to.be.reverted` does not work

### ISSUE THREAD

**Issue by fredfortier** [EthWorks/Waffle#95]
I followed the exact syntax in the docs and receive this output.
```
AssertionError: Expected transaction to be reverted
Expected :not reverted
Actual   :reverted
```
It seems backwards. I can confirm that the tx was reverted. Other `expect` properties like `to.emit` seems to work. There is no difference in how I call them. I'm using a `Web3Provider` connected to an external `ganache-cli` client.

**Comment by marekkirejczyk** [comment]
Would you pste the code (solidity and test) you are using.

**Comment by fredfortier** [comment]
The contracts that I'm using are complicated to reference here. I can try to replicate it with a simpler contract. In the meantime, can you tell me if using a `ether.provides.Web3` that connects to a running Ganache instance (not one created by `createMockProvider`) is supported? If so, what version of `ganache-cli`?

**Comment by fredfortier** [comment]
See PR above. The problem is that the `reason.toString()` does not serialize the transaction response given by Ganache properly (it serializes it as `[Object]`), so I include a condition that extracts the `message` attribute if available. If you think it's the right approach, I'll add a unit test.

**Comment by fredfortier** [comment]
Fixed with PR #96

**Comment by cacampbell** [comment]
Hi, this blatantly does not work, still. 

```
function call() public {
require(false, "Revert");
}

```

```
expect(contract.call()).to.be.reverted;
```

```
      AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.

```

**Comment by marekkirejczyk** [comment]
@msieczko Would you know anything about it?

**Comment by marekkirejczyk** [comment]
@fredfortier @cacampbell Does `revertWith` work in your case?

**Comment by cacampbell** [comment]
Same for `to.be.reverted` and `to.be.revertedWith(message)` I'm afraid. 

I am 95% this has something to do with the hardhat evm -- as the revert statements do work when testing against just a locally deployed evm using a jsonrpc client

**Comment by elhil** [comment]
This is happening to me non-deterministically. Sometimes changing the test to call a different contract method and then changing it back fixes it. No idea what's happening but happy to provide more feedback.

**Comment by elhil** [comment]
I'm using `hardhat-ethers` 2.0.2 and `hardhat-waffle `2.0.1`, which are at this time the latest.

**Comment by snwokenk** [comment]
An issue for me too

**Comment by snwokenk** [comment]
for some reason doing  this works:

```
const response = await Token.method()

await expect(response.wait()).to.be.reverted
```
In my case doing this is the only way Token.method() actually will work for any other assertions.

I'm using a forked version of ethereum mainnet with hardhat.

**Comment by pasevin** [comment]
For me ```.to.be.revertedWith``` works, but the message string can be anything and it will still pass.
By works I mean, if the method doesn't revert, the test will fail. 
So it kind of works, but not as it should be.

As for ```.to.be.reverted```, no proposed workarounds work...

I'm using hardhat v2.2.1

**Comment by psykeeper** [comment]
Commented this on another thread https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/155#issuecomment-886127598

I was having a similar issue but was able to get it to work by:

1. Removing `chai-as-promised`
2. Installing `ethereum-waffle` 
3. Setting up `chai` with the following initialization code:

```javascript
const hre = require("hardhat");
const chai = require("chai");
const { solidity } = require("ethereum-waffle");
chai.use(solidity);
const { expect } = chai;
```

The issue I ran into was the `expect` object not having waffle's matchers. Specifically, `expect` didn't know about `reverted` without having `ethereum-waffle` installed and `chai` initialized with `solidity` from `ethereum-waffle`.

**Comment by 0xpApaSmURf** [comment]
```
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@nomiclabs/hardhat-web3": "^2.0.0",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.4.4",
    "hardhat": "^2.6.0",
    "web3": "^1.5.2"
```

```javascript
await expect(contract.revert()).to.be.ok; // always passes even though a reverting transaction should not be ok
await expect(contract.revert()).to.be.revertedWith("literally anything"); // always passes no matter what revert message
```

Please re-open.

**Comment by neelansh15** [comment]
> for some reason doing this works:
> 
> ```
> const response = await Token.method()
> 
> await expect(response.wait()).to.be.reverted
> ```
> 
> In my case doing this is the only way Token.method() actually will work for any other assertions.
> 
> I'm using a forked version of ethereum mainnet with hardhat.

This worked for me perfectly on hardhat. awaiting the `expect(...).to.be.revertedWith(...)` made sure that it doesn't always pass and waits for it to be completed (otherwise it would pass every time with 0ms time).

**Comment by itinance** [comment]
Can confirm that `.to.be.revertedWith` will be always successful although nothing has reverted, and vice versa.

```
"ethereum-waffle": "^3.4.0",
"hardhat": "^2.7.1"
"ethers": "^5.5.2",

```

**Comment by eherms** [comment]
Ugh.  Having same issue.  Definitely reverts but test failing even with the await expect(response.wait()).to.be.reverted .

**Comment by eherms** [comment]
> Ugh. Having same issue. Definitely reverts but test failing even with the await expect(response.wait()).to.be.reverted .

Getting rid of the await fixed it.  expect(Token.method()).to.be.reverted worked for me as expected.

**Comment by 0xpApaSmURf** [comment]
> Getting rid of the await fixed it. expect(Token.method()).to.be.reverted worked for me as expected.

Have you tried narrowing the expected results? As shown in my example, it will report to revert successfully even if I pass in a garbage revert message.

**Comment by jd2791** [comment]
> > Getting rid of the await fixed it. expect(Token.method()).to.be.reverted worked for me as expected.
> 
> Have you tried narrowing the expected results? As shown in my example, it will report to revert successfully even if I pass in a garbage revert message.

I'm getting the same result with `revertedWith` where it reports a successful revert even if the message doesn't match with what I'm expecting. 

Putting the `await` on the entire expression worked for me; the revert is successfully expected and fails if the revert message does not match:

`await expect(someFn()).to.be.revertedWith('Some revrt message'); // intentional typo on 'revrt'` 

results in

`AssertionError: Expected transaction to be reverted with Some revrt message, but other exception was thrown: Error: VM Exception while processing transaction: reverted with reason string 'Some revert message'`

**Comment by smallyunet** [comment]
I occur the same problem. I find it not work because testing a single file such as:

```
npx hardhat test ./test/initialize.ts 
```

But it works while running full tests:

```
npx hardhat test
```

**Comment by DINDX** [comment]
> > > Getting rid of the await fixed it. expect(Token.method()).to.be.reverted worked for me as expected.
> > 
> > 
> > Have you tried narrowing the expected results? As shown in my example, it will report to revert successfully even if I pass in a garbage revert message.
> 
> I'm getting the same result with `revertedWith` where it reports a successful revert even if the message doesn't match with what I'm expecting.
> 
> Putting the `await` on the entire expression worked for me; the revert is successfully expected and fails if the revert message does not match:
> 
> `await expect(someFn()).to.be.revertedWith('Some revrt message'); // intentional typo on 'revrt'`
> 
> results in
> 
> `AssertionError: Expected transaction to be reverted with Some revrt message, but other exception was thrown: Error: VM Exception while processing transaction: reverted with reason string 'Some revert message'`

Leaving in the `await` and using `--network hardhat` instead of `--network kovan` is what worked for me, as per the suggestion of @cacampbell above. What network are you using @jd2791?

**Comment by sergane13** [comment]
Have you found a solution to this problem? I have tested both locally, on hardhat, on rinkeby, and to.be.reverted seems to be invisible for Waffle.

**Comment by captainkidd5** [comment]
Also having this issue when testing against rinkeby with hardhat. I find that the revert message is working as intended only for "revert" within a contract, but NOT for "require".

**Comment by Kayaba-Attribution** [comment]
Found the solution to be the following:
instead of 
```javascript
expect(await myContract.connect(bob).deposit()).to.be.reverted;
```
use
```javascript
await expect(myContract.connect(bob).deposit()).to.be.reverted;
```

**Comment by hmalkawi1** [comment]
> > Found the solution to be the following: instead of
> > ```js
> > expect(await myContract.connect(bob).deposit()).to.be.reverted;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > use
> > ```js
> > await expect(myContract.connect(bob).deposit()).to.be.reverted;
> > ```
> 
> This is correct, if you look at the page for [Waffle Chai matchers](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html) only the BigNumbers matchers use `expect(await)`, all other matchers are shown using `await expect()`.

You're an actual King...

**Comment by artem-bayandin** [comment]
Hi,
Experiencing a similar issue when trying to validate the revert message of a transaction (for 'pure' / 'view' functions I can read the revert message). I use hardhat, typescript.

On top of my file with typescript tests:
```
import { ethers } from 'hardhat'
import chai from 'chai'
import 'ethereum-waffle'
import { solidity } from 'ethereum-waffle'
chai.use(solidity)
const { expect } = chai
```

`contract.funcWithRevert()` runs as a transaction (neither `pure` nor `view` modifier) and has validation like `require(someValidation, "Validation Failed");`

The next test works (tests that tx is reverted):
```
let tx = await contract.connect(user1).funcWithRevert()
await expect(tx.wait()).to.be.reverted
```

The next test fails
```
let tx = await contract.connect(user1).funcWithRevert()
await expect(tx.wait()).to.be.revertedWith("Validation Failed")
```

In test results I see:
`
AssertionError: Expected transaction to be reverted with Validation Failed, but other exception was thrown: Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0xd927d6cd4941661fe9cd8c26d2b777d7f03336fc56211e567846d6478fdca24f", transaction={"hash":"0xd927d6cd4941661fe9cd8c26d2b777d7f03336fc56211e567846d6478fdca24f","type":0,"accessList":null,"blockHash":"0xd6581265a8bad323cb6c789c35f21846af68cf5d8e3480af004be0a4ce19e8f3","blockNumber":28,"transactionIndex":0,"confirmations":1,"from":"0x70997970C51812dc3A010C7d01b50e0d17dc79C8","gasPrice":{"type":"BigNumber","hex":"0x1087ee0600"},"gasLimit":{"type":"BigNumber","hex":"0x2e1f58"},"to":"0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE","value":{"type":"BigNumber","hex":"0x00"},"nonce":1,"data":"0x80dff85d0000000000000000000000009fe46736679d2d9a65f0992f2272de9f3c7fa6e0","r":"0x1807c35b397648bc009b42b47c72f9fd2b3006f63887556db86564189841cafc","s":"0x793f0570bcee3d658e2bfa0ee14478dc1e1972a5d864eb457c6f8d71036c44ec","v":254040,"creates":null,"chainId":127002}, receipt={"to":"0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE","from":"0x70997970C51812dc3A010C7d01b50e0d17dc79C8","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x92bf"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xd6581265a8bad323cb6c789c35f21846af68cf5d8e3480af004be0a4ce19e8f3","transactionHash":"0xd927d6cd4941661fe9cd8c26d2b777d7f03336fc56211e567846d6478fdca24f","logs":[],"blockNumber":28,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x92bf"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x1087ee0600"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.6.1)
`

**Comment by DorianDaSilva** [comment]
@eherms This works...so simple. thanks!

**Comment by Abstrucked** [comment]
> > > Getting rid of the await fixed it. expect(Token.method()).to.be.reverted worked for me as expected.
> > 
> > 
> > Have you tried narrowing the expected results? As shown in my example, it will report to revert successfully even if I pass in a garbage revert message.
> 
> I'm getting the same result with `revertedWith` where it reports a successful revert even if the message doesn't match with what I'm expecting.
> 
> Putting the `await` on the entire expression worked for me; the revert is successfully expected and fails if the revert message does not match:
> 
> `await expect(someFn()).to.be.revertedWith('Some revrt message'); // intentional typo on 'revrt'`
> 
> results in
> 
> `AssertionError: Expected transaction to be reverted with Some revrt message, but other exception was thrown: Error: VM Exception while processing transaction: reverted with reason string 'Some revert message'`

this worked for me..

**Comment by ghana7989** [comment]
> 
this solution worked
kind of new here what do you mean by BigNumber matches, in this context?

**Comment by ghana7989** [comment]
> > Found the solution to be the following: instead of
> > ```js
> > expect(await myContract.connect(bob).deposit()).to.be.reverted;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > use
> > ```js
> > await expect(myContract.connect(bob).deposit()).to.be.reverted;
> > ```
> 
> This is correct, if you look at the page for [Waffle Chai matchers](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html) only the BigNumbers matchers use `expect(await)`, all other matchers are shown using `await expect()`.

this solution worked
kind of new here what do you mean by BigNumber matches, in this context?

**Comment by roadbuilder** [comment]
Still not working if there are multiple providers being used for multichain. The await expect to.be.revertedWith doesn't catch the actual revert and gives an error message with the actual revert

**Comment by rzadp** [comment]
> Still not working if there are multiple providers being used for multichain. The await expect to.be.revertedWith doesn't catch the actual revert and gives an error message with the actual revert

@roadbuilder Is this helpful perhaps? https://github.com/TrueFiEng/Waffle/issues/813#event-7807384227
